apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: elector-js
  name: elector-js
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: elector-js
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: elector-js 
    spec:
      containers:
      - image: brendanburns/elector
        imagePullPolicy: Always
        name: elector
        resources: {}
      - image: brendanburns/sync-js
        name: example
        command:
        - node
        - elector.js
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
